# Generated by Django 3.2.9 on 2021-11-01 17:21

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Neighbourhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood')),
            ],
        ),
    ]
