# Generated by Django 3.2.9 on 2021-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
