# Generated by Django 3.2.9 on 2021-11-05 08:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_descrition_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
