# Generated by Django 3.2.9 on 2021-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_neighbourhood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
