# Generated by Django 3.2.9 on 2021-11-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_neighbourhood_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='image',
        ),
    ]
